import { test, expect } from 'vitest';
import { assertFormat } from './utils.ts';

const date = 3290.1278435; // 1909-01-02 03:04:05.678

test('Date specifiers:', () => {
  expect.assertions(85);
  assertFormat('s', date, '6');
  assertFormat('ss', date, '06');
  assertFormat('sss', date, '06');
  assertFormat('ssss', date, '06');
  assertFormat('sssss', date, '06');
  assertFormat('ssssss', date, '06');
  assertFormat('S', date, '6');
  assertFormat('SS', date, '06');
  assertFormat('SSS', date, '06');
  assertFormat('SSSS', date, '06');
  assertFormat('SSSSS', date, '06');
  assertFormat('SSSSSS', date, '06');
  assertFormat('m', date, '1');
  assertFormat('mm', date, '01');
  assertFormat('mmm', date, 'Jan');
  assertFormat('mmmm', date, 'January');
  assertFormat('mmmmm', date, 'J');
  assertFormat('mmmmmm', date, 'January');
  assertFormat('M', date, '1');
  assertFormat('MM', date, '01');
  assertFormat('MMM', date, 'Jan');
  assertFormat('MMMM', date, 'January');
  assertFormat('MMMMM', date, 'J');
  assertFormat('MMMMMM', date, 'January');
  assertFormat('h', date, '3');
  assertFormat('hh', date, '03');
  assertFormat('hhh', date, '03');
  assertFormat('hhhh', date, '03');
  assertFormat('hhhhh', date, '03');
  assertFormat('hhhhhh', date, '03');
  assertFormat('H', date, '3');
  assertFormat('HH', date, '03');
  assertFormat('HHH', date, '03');
  assertFormat('HHHH', date, '03');
  assertFormat('HHHHH', date, '03');
  assertFormat('HHHHHH', date, '03');
  assertFormat('a', date, 'a');
  assertFormat('aa', date, 'aa');
  assertFormat('aaa', date, 'Sat');
  assertFormat('aaaa', date, 'Saturday');
  assertFormat('aaaaa', date, 'Saturday');
  assertFormat('aaaaaa', date, 'Saturday');
  assertFormat('d', date, '2');
  assertFormat('dd', date, '02');
  assertFormat('ddd', date, 'Sat');
  assertFormat('dddd', date, 'Saturday');
  assertFormat('ddddd', date, 'Saturday');
  assertFormat('dddddd', date, 'Saturday');
  assertFormat('D', date, '2');
  assertFormat('DD', date, '02');
  assertFormat('DDD', date, 'Sat');
  assertFormat('DDDD', date, 'Saturday');
  assertFormat('DDDDD', date, 'Saturday');
  assertFormat('DDDDDD', date, 'Saturday');
  assertFormat('y', date, '09');
  assertFormat('yy', date, '09');
  assertFormat('yyy', date, '1909');
  assertFormat('yyyy', date, '1909');
  assertFormat('yyyyy', date, '1909');
  assertFormat('yyyyyy', date, '1909');
  assertFormat('Y', date, '09');
  assertFormat('YY', date, '09');
  assertFormat('YYY', date, '1909');
  assertFormat('YYYY', date, '1909');
  assertFormat('YYYYY', date, '1909');
  assertFormat('YYYYYY', date, '1909');
  // elapsed
  assertFormat('[h]', date, '78963');
  assertFormat('[hh]', date, '78963');
  assertFormat('[hhh]', date, '78963');
  assertFormat('[hhhh]', date, '78963');
  assertFormat('[hhhhh]', date, '78963');
  assertFormat('[m]', date, '4737784');
  assertFormat('[mm]', date, '4737784');
  assertFormat('[mmm]', date, '4737784');
  assertFormat('[mmmm]', date, '4737784');
  assertFormat('[s]', date, '284267046');
  assertFormat('[ss]', date, '284267046');
  assertFormat('[sss]', date, '284267046');
  assertFormat('[ssss]', date, '284267046');
  // fractional seconds
  assertFormat('[s].0', date, '284267045.7');
  assertFormat('[s].00', date, '284267045.68');
  assertFormat('[s].000', date, '284267045.678');
  assertFormat('s.0', date, '5.7');
  assertFormat('s.00', date, '5.68');
  assertFormat('s.000', date, '5.678');
});

test('Date specifiers: month vs. minute', () => {
  expect.assertions(61);
  assertFormat('h', date, '3');
  assertFormat('m', date, '1');
  assertFormat('s', date, '6');

  assertFormat('h-h', date, '3-3');
  assertFormat('h-m', date, '3-4');
  assertFormat('h-s', date, '3-6');
  assertFormat('m-h', date, '1-3');
  assertFormat('m-m', date, '1-1');
  assertFormat('m-s', date, '4-6');
  assertFormat('s-h', date, '6-3');
  assertFormat('s-m', date, '6-4');
  assertFormat('s-s', date, '6-6');

  assertFormat('h-h-m', date, '3-3-4');
  assertFormat('h-h-s', date, '3-3-6');
  assertFormat('h-m-h', date, '3-4-3');
  assertFormat('h-m-m', date, '3-4-1');
  assertFormat('h-m-s', date, '3-4-6');
  assertFormat('h-s-h', date, '3-6-3');
  assertFormat('h-s-m', date, '3-6-4');
  assertFormat('h-s-s', date, '3-6-6');
  assertFormat('m-h-h', date, '1-3-3');
  assertFormat('m-h-m', date, '1-3-4');
  assertFormat('m-h-s', date, '1-3-6');
  assertFormat('m-m-h', date, '1-1-3');
  assertFormat('m-m-m', date, '1-1-1');
  assertFormat('m-m-s', date, '1-4-6');
  assertFormat('m-s-h', date, '4-6-3');
  assertFormat('m-s-m', date, '4-6-1');
  assertFormat('m-s-s', date, '4-6-6');
  assertFormat('s-h-h', date, '6-3-3');
  assertFormat('s-h-m', date, '6-3-4');
  assertFormat('s-h-s', date, '6-3-6');
  assertFormat('s-m-h', date, '6-4-3');
  assertFormat('s-m-m', date, '6-4-1');
  assertFormat('s-m-s', date, '6-4-6');
  assertFormat('s-s-h', date, '6-6-3');
  assertFormat('s-s-m', date, '6-6-4');

  assertFormat('h-m-m-s', date, '3-4-4-6');
  assertFormat('h-m-s-m', date, '3-4-6-1');
  assertFormat('h-s-m-m', date, '3-6-4-1');
  assertFormat('m-h-m-s', date, '1-3-4-6');
  assertFormat('m-h-s-m', date, '1-3-6-4');
  assertFormat('m-m-h-s', date, '1-1-3-6');
  assertFormat('m-m-s-h', date, '1-4-6-3');
  assertFormat('m-s-h-m', date, '4-6-3-4');
  assertFormat('m-s-m-h', date, '4-6-1-3');
  assertFormat('s-h-m-m', date, '6-3-4-1');
  assertFormat('s-m-h-m', date, '6-4-3-4');
  assertFormat('s-m-m-h', date, '6-4-1-3');

  assertFormat('y-m-d', date, '09-1-2');
  assertFormat('d-m-y', date, '2-1-09');
  assertFormat('yy-mm-dd', date, '09-01-02');

  assertFormat('yyyy', date, '1909');
  assertFormat('yyyy-mm', date, '1909-01');
  assertFormat('yyyy-mm-dd', date, '1909-01-02');
  assertFormat('yyyy-mm-dd\\Thh', date, '1909-01-02T03');
  assertFormat('yyyy-mm-dd\\Thh-mm', date, '1909-01-02T03-04');
  assertFormat('yyyy-mm-dd\\Thh-mm-ss', date, '1909-01-02T03-04-06');
  assertFormat('yyyy-mm-dd\\Thh-mm-ss.000', date, '1909-01-02T03-04-05.678');

  assertFormat('yyyy-mm-dd\\Thh-mm-ss.000', 60, '1900-02-29T00-00-00.000');
  assertFormat('yyyy-mm-dd\\Thh-mm-ss.000', 61, '1900-03-01T00-00-00.000');
});
