import { expect, test } from 'vitest';
import { format } from '../lib/index.ts';

const date = 3290.1278435; // 1909-01-02 03:04:05.678

test('Date specifiers:', () => {
  expect(format('s', date)).toBe('6');
  expect(format('ss', date)).toBe('06');
  expect(format('sss', date)).toBe('06');
  expect(format('ssss', date)).toBe('06');
  expect(format('sssss', date)).toBe('06');
  expect(format('ssssss', date)).toBe('06');
  expect(format('S', date)).toBe('6');
  expect(format('SS', date)).toBe('06');
  expect(format('SSS', date)).toBe('06');
  expect(format('SSSS', date)).toBe('06');
  expect(format('SSSSS', date)).toBe('06');
  expect(format('SSSSSS', date)).toBe('06');
  expect(format('m', date)).toBe('1');
  expect(format('mm', date)).toBe('01');
  expect(format('mmm', date)).toBe('Jan');
  expect(format('mmmm', date)).toBe('January');
  expect(format('mmmmm', date)).toBe('J');
  expect(format('mmmmmm', date)).toBe('January');
  expect(format('M', date)).toBe('1');
  expect(format('MM', date)).toBe('01');
  expect(format('MMM', date)).toBe('Jan');
  expect(format('MMMM', date)).toBe('January');
  expect(format('MMMMM', date)).toBe('J');
  expect(format('MMMMMM', date)).toBe('January');
  expect(format('h', date)).toBe('3');
  expect(format('hh', date)).toBe('03');
  expect(format('hhh', date)).toBe('03');
  expect(format('hhhh', date)).toBe('03');
  expect(format('hhhhh', date)).toBe('03');
  expect(format('hhhhhh', date)).toBe('03');
  expect(format('H', date)).toBe('3');
  expect(format('HH', date)).toBe('03');
  expect(format('HHH', date)).toBe('03');
  expect(format('HHHH', date)).toBe('03');
  expect(format('HHHHH', date)).toBe('03');
  expect(format('HHHHHH', date)).toBe('03');
  expect(format('a', date)).toBe('a');
  expect(format('aa', date)).toBe('aa');
  expect(format('aaa', date)).toBe('Sat');
  expect(format('aaaa', date)).toBe('Saturday');
  expect(format('aaaaa', date)).toBe('Saturday');
  expect(format('aaaaaa', date)).toBe('Saturday');
  expect(format('d', date)).toBe('2');
  expect(format('dd', date)).toBe('02');
  expect(format('ddd', date)).toBe('Sat');
  expect(format('dddd', date)).toBe('Saturday');
  expect(format('ddddd', date)).toBe('Saturday');
  expect(format('dddddd', date)).toBe('Saturday');
  expect(format('D', date)).toBe('2');
  expect(format('DD', date)).toBe('02');
  expect(format('DDD', date)).toBe('Sat');
  expect(format('DDDD', date)).toBe('Saturday');
  expect(format('DDDDD', date)).toBe('Saturday');
  expect(format('DDDDDD', date)).toBe('Saturday');
  expect(format('y', date)).toBe('09');
  expect(format('yy', date)).toBe('09');
  expect(format('yyy', date)).toBe('1909');
  expect(format('yyyy', date)).toBe('1909');
  expect(format('yyyyy', date)).toBe('1909');
  expect(format('yyyyyy', date)).toBe('1909');
  expect(format('Y', date)).toBe('09');
  expect(format('YY', date)).toBe('09');
  expect(format('YYY', date)).toBe('1909');
  expect(format('YYYY', date)).toBe('1909');
  expect(format('YYYYY', date)).toBe('1909');
  expect(format('YYYYYY', date)).toBe('1909');
  // elapsed
  expect(format('[h]', date)).toBe('78963');
  expect(format('[hh]', date)).toBe('78963');
  expect(format('[hhh]', date)).toBe('78963');
  expect(format('[hhhh]', date)).toBe('78963');
  expect(format('[hhhhh]', date)).toBe('78963');
  expect(format('[m]', date)).toBe('4737784');
  expect(format('[mm]', date)).toBe('4737784');
  expect(format('[mmm]', date)).toBe('4737784');
  expect(format('[mmmm]', date)).toBe('4737784');
  expect(format('[s]', date)).toBe('284267046');
  expect(format('[ss]', date)).toBe('284267046');
  expect(format('[sss]', date)).toBe('284267046');
  expect(format('[ssss]', date)).toBe('284267046');
  // fractional seconds
  expect(format('[s].0', date)).toBe('284267045.7');
  expect(format('[s].00', date)).toBe('284267045.68');
  expect(format('[s].000', date)).toBe('284267045.678');
  expect(format('s.0', date)).toBe('5.7');
  expect(format('s.00', date)).toBe('5.68');
  expect(format('s.000', date)).toBe('5.678');
});

test('Date specifiers: month vs. minute', () => {
  expect(format('h', date)).toBe('3');
  expect(format('m', date)).toBe('1');
  expect(format('s', date)).toBe('6');

  expect(format('h-h', date)).toBe('3-3');
  expect(format('h-m', date)).toBe('3-4');
  expect(format('h-s', date)).toBe('3-6');
  expect(format('m-h', date)).toBe('1-3');
  expect(format('m-m', date)).toBe('1-1');
  expect(format('m-s', date)).toBe('4-6');
  expect(format('s-h', date)).toBe('6-3');
  expect(format('s-m', date)).toBe('6-4');
  expect(format('s-s', date)).toBe('6-6');

  expect(format('h-h-m', date)).toBe('3-3-4');
  expect(format('h-h-s', date)).toBe('3-3-6');
  expect(format('h-m-h', date)).toBe('3-4-3');
  expect(format('h-m-m', date)).toBe('3-4-1');
  expect(format('h-m-s', date)).toBe('3-4-6');
  expect(format('h-s-h', date)).toBe('3-6-3');
  expect(format('h-s-m', date)).toBe('3-6-4');
  expect(format('h-s-s', date)).toBe('3-6-6');
  expect(format('m-h-h', date)).toBe('1-3-3');
  expect(format('m-h-m', date)).toBe('1-3-4');
  expect(format('m-h-s', date)).toBe('1-3-6');
  expect(format('m-m-h', date)).toBe('1-1-3');
  expect(format('m-m-m', date)).toBe('1-1-1');
  expect(format('m-m-s', date)).toBe('1-4-6');
  expect(format('m-s-h', date)).toBe('4-6-3');
  expect(format('m-s-m', date)).toBe('4-6-1');
  expect(format('m-s-s', date)).toBe('4-6-6');
  expect(format('s-h-h', date)).toBe('6-3-3');
  expect(format('s-h-m', date)).toBe('6-3-4');
  expect(format('s-h-s', date)).toBe('6-3-6');
  expect(format('s-m-h', date)).toBe('6-4-3');
  expect(format('s-m-m', date)).toBe('6-4-1');
  expect(format('s-m-s', date)).toBe('6-4-6');
  expect(format('s-s-h', date)).toBe('6-6-3');
  expect(format('s-s-m', date)).toBe('6-6-4');

  expect(format('h-m-m-s', date)).toBe('3-4-4-6');
  expect(format('h-m-s-m', date)).toBe('3-4-6-1');
  expect(format('h-s-m-m', date)).toBe('3-6-4-1');
  expect(format('m-h-m-s', date)).toBe('1-3-4-6');
  expect(format('m-h-s-m', date)).toBe('1-3-6-4');
  expect(format('m-m-h-s', date)).toBe('1-1-3-6');
  expect(format('m-m-s-h', date)).toBe('1-4-6-3');
  expect(format('m-s-h-m', date)).toBe('4-6-3-4');
  expect(format('m-s-m-h', date)).toBe('4-6-1-3');
  expect(format('s-h-m-m', date)).toBe('6-3-4-1');
  expect(format('s-m-h-m', date)).toBe('6-4-3-4');
  expect(format('s-m-m-h', date)).toBe('6-4-1-3');

  expect(format('y-m-d', date)).toBe('09-1-2');
  expect(format('d-m-y', date)).toBe('2-1-09');
  expect(format('yy-mm-dd', date)).toBe('09-01-02');

  expect(format('yyyy', date)).toBe('1909');
  expect(format('yyyy-mm', date)).toBe('1909-01');
  expect(format('yyyy-mm-dd', date)).toBe('1909-01-02');
  expect(format('yyyy-mm-dd\\Thh', date)).toBe('1909-01-02T03');
  expect(format('yyyy-mm-dd\\Thh-mm', date)).toBe('1909-01-02T03-04');
  expect(format('yyyy-mm-dd\\Thh-mm-ss', date)).toBe('1909-01-02T03-04-06');
  expect(format('yyyy-mm-dd\\Thh-mm-ss.000', date)).toBe('1909-01-02T03-04-05.678');

  expect(format('yyyy-mm-dd\\Thh-mm-ss.000', 60)).toBe('1900-02-29T00-00-00.000');
  expect(format('yyyy-mm-dd\\Thh-mm-ss.000', 61)).toBe('1900-03-01T00-00-00.000');
});

