import { test, expect } from 'vitest';
import { assertValidFormat } from './utils.ts';

test('Validity tests', () => {
  expect.assertions(435);
  assertValidFormat('" Excellent"');
  assertValidFormat('" Fair"');
  assertValidFormat('" Good"');
  assertValidFormat('" Poor"');
  assertValidFormat('" Very Good"');
  assertValidFormat('"$"#,##0');
  assertValidFormat('"$"#,##0.00');
  assertValidFormat('"$"#,##0.00_);[Red]\\("$"#,##0.00\\)');
  assertValidFormat('"$"#,##0.00_);\\("$"#,##0.00\\)');
  assertValidFormat('"$"#,##0;[Red]\\-"$"#,##0');
  assertValidFormat('"$"#,##0_);[Red]\\("$"#,##0\\)');
  assertValidFormat('"$"#,##0_);\\("$"#,##0\\)');
  assertValidFormat('"Haha!"\\ @\\ "Yeah!"');
  assertValidFormat('"TRUE";"TRUE";"FALSE"');
  assertValidFormat('"True";"True";"False";@');
  assertValidFormat('"Years: "0');
  assertValidFormat('"Yes";"Yes";"No";@');
  assertValidFormat('"kl "hh:mm:ss;@');
  assertValidFormat('"£"#,##0.00');
  assertValidFormat('"£"#,##0;[Red]\\-"£"#,##0');
  assertValidFormat('"€"#,##0.00');
  assertValidFormat('"€"\\ #,##0.00_-');
  assertValidFormat('"上午/下午 "hh"時"mm"分"ss"秒 "');
  assertValidFormat('"￥"#,##0.00;"￥"\\-#,##0.00');
  assertValidFormat('#');
  assertValidFormat('# ?/?');
  assertValidFormat('# ??/??');
  assertValidFormat('#" "?/?');
  assertValidFormat('#" "??/??');
  assertValidFormat('#"abded"\\ ??/??');
  assertValidFormat('###0.00;-###0.00');
  assertValidFormat('###0;-###0');
  assertValidFormat('##0.0E+0');
  assertValidFormat('#,##0');
  assertValidFormat('#,##0 ;(#,##0)');
  assertValidFormat('#,##0 ;[Red](#,##0)');
  assertValidFormat('#,##0"р.";[Red]\\-#,##0"р."');
  assertValidFormat('#,##0.0');
  assertValidFormat('#,##0.00');
  assertValidFormat('#,##0.00 "�"');
  assertValidFormat('#,##0.00 €;-#,##0.00 €');
  assertValidFormat('#,##0.00"р.";[Red]\\-#,##0.00"р."');
  assertValidFormat('#,##0.000');
  assertValidFormat('#,##0.0000');
  assertValidFormat('#,##0.00000');
  assertValidFormat('#,##0.000000');
  assertValidFormat('#,##0.0000000');
  assertValidFormat('#,##0.00000000');
  assertValidFormat('#,##0.000000000');
  assertValidFormat('#,##0.00000000;[Red]#,##0.00000000');
  assertValidFormat('#,##0.0000_ ');
  assertValidFormat('#,##0.000_ ');
  assertValidFormat('#,##0.000_);\\(#,##0.000\\)');
  assertValidFormat('#,##0.00;(#,##0.00)');
  assertValidFormat('#,##0.00;(#,##0.00);0.00');
  assertValidFormat('#,##0.00;[Red](#,##0.00)');
  assertValidFormat('#,##0.00;[Red]\\(#,##0.00\\)');
  assertValidFormat('#,##0.00;\\(#,##0.00\\)');
  assertValidFormat('#,##0.00[$₹-449]_);\\(#,##0.00[$₹-449]\\)');
  assertValidFormat('#,##0.00\\ "р."');
  assertValidFormat('#,##0.00\\ "р.";[Red]\\-#,##0.00\\ "р."');
  assertValidFormat('#,##0.00\\ [$€-407]');
  assertValidFormat('#,##0.00\\ [$€-40C]');
  assertValidFormat('#,##0.00_);\\(#,##0.00\\)');
  assertValidFormat('#,##0.00_р_.;[Red]\\-#,##0.00_р_.');
  assertValidFormat('#,##0.00_р_.;\\-#,##0.00_р_.');
  assertValidFormat('#,##0.0;[Red]#,##0.0');
  assertValidFormat('#,##0.0_ ;\\-#,##0.0\\ ');
  assertValidFormat('#,##0.0_);[Red]\\(#,##0.0\\)');
  assertValidFormat('#,##0.0_);\\(#,##0.0\\)');
  assertValidFormat('#,##0;\\-#,##0;0');
  assertValidFormat('#,##0\\ "р.";[Red]\\-#,##0\\ "р."');
  assertValidFormat('#,##0\\ "р.";\\-#,##0\\ "р."');
  assertValidFormat('#,##0\\ ;[Red]\\(#,##0\\)');
  assertValidFormat('#,##0\\ ;\\(#,##0\\)');
  assertValidFormat('#,##0_ ');
  assertValidFormat('#,##0_ ;[Red]\\-#,##0\\ ');
  assertValidFormat('#,##0_);[Red]\\(#,##0\\)');
  assertValidFormat('#,##0_р_.;[Red]\\-#,##0_р_.');
  assertValidFormat('#,##0_р_.;\\-#,##0_р_.');
  assertValidFormat('#.0000,,');
  assertValidFormat('#0');
  assertValidFormat('#0.00');
  assertValidFormat('#0.0000');
  assertValidFormat('#\\ ?/10');
  assertValidFormat('#\\ ?/2');
  assertValidFormat('#\\ ?/4');
  assertValidFormat('#\\ ?/8');
  assertValidFormat('#\\ ?/?');
  assertValidFormat('#\\ ??/100');
  assertValidFormat('#\\ ??/100;[Red]\\(#\\ ??/16\\)');
  assertValidFormat('#\\ ??/16');
  assertValidFormat('#\\ ??/??');
  assertValidFormat('#\\ ??/?????????');
  assertValidFormat('#\\ ???/???');
  assertValidFormat('**\\ #,###,#00,000.00,**');
  assertValidFormat('0');
  assertValidFormat('0"abde".0"??"000E+00');
  assertValidFormat('0%');
  assertValidFormat('0.0');
  assertValidFormat('0.0%');
  assertValidFormat('0.00');
  assertValidFormat('0.00"°"');
  assertValidFormat('0.00%');
  assertValidFormat('0.000');
  assertValidFormat('0.000%');
  assertValidFormat('0.0000');
  assertValidFormat('0.000000');
  assertValidFormat('0.00000000');
  assertValidFormat('0.000000000');
  assertValidFormat('0.000000000%');
  assertValidFormat('0.00000000000');
  assertValidFormat('0.000000000000000');
  assertValidFormat('0.00000000E+00');
  assertValidFormat('0.0000E+00');
  assertValidFormat('0.00;[Red]0.00');
  assertValidFormat('0.00E+00');
  assertValidFormat('0.00_);[Red]\\(0.00\\)');
  assertValidFormat('0.00_);\\(0.00\\)');
  assertValidFormat('0.0_ ');
  assertValidFormat('00.00.00.000');
  assertValidFormat('00.000%');
  assertValidFormat('0000');
  assertValidFormat('00000');
  assertValidFormat('00000000');
  assertValidFormat('000000000');
  assertValidFormat('00000\\-0000');
  assertValidFormat('00000\\-00000');
  assertValidFormat('000\\-00\\-0000');
  assertValidFormat('0;[Red]0');
  assertValidFormat('0\\-00000\\-00000\\-0');
  assertValidFormat('0_);[Red]\\(0\\)');
  assertValidFormat('0_);\\(0\\)');
  assertValidFormat('@');
  assertValidFormat('A/P');
  assertValidFormat('AM/PM');
  assertValidFormat('AM/PMh"時"mm"分"ss"秒";@');
  assertValidFormat('D');
  assertValidFormat('DD');
  assertValidFormat('DD/MM/YY;@');
  assertValidFormat('DD/MM/YYYY');
  assertValidFormat('DD/MM/YYYY;@');
  assertValidFormat('DDD');
  assertValidFormat('DDDD');
  assertValidFormat('DDDD", "MMMM\\ DD", "YYYY');
  assertValidFormat('GENERAL');
  assertValidFormat('General');
  assertValidFormat('H');
  assertValidFormat('H:MM:SS\\ AM/PM');
  assertValidFormat('HH:MM');
  assertValidFormat('HH:MM:SS\\ AM/PM');
  assertValidFormat('HHM');
  assertValidFormat('HHMM');
  assertValidFormat('HH[MM]');
  assertValidFormat('HH[M]');
  assertValidFormat('M/D/YYYY');
  assertValidFormat('M/D/YYYY\\ H:MM');
  assertValidFormat('MM/DD/YY');
  assertValidFormat('S');
  assertValidFormat('SS');
  assertValidFormat('YY');
  assertValidFormat('YYM');
  assertValidFormat('YYMM');
  assertValidFormat('YYMMM');
  assertValidFormat('YYMMMM');
  assertValidFormat('YYMMMMM');
  assertValidFormat('YYYY');
  assertValidFormat('YYYY-MM-DD HH:MM:SS');
  assertValidFormat('YYYY\\-MM\\-DD');
  assertValidFormat('[$$-409]#,##0');
  assertValidFormat('[$$-409]#,##0.00');
  assertValidFormat('[$$-409]#,##0.00_);[Red]\\([$$-409]#,##0.00\\)');
  assertValidFormat('[$$-C09]#,##0.00');
  assertValidFormat('[$-100042A]h:mm:ss\\ AM/PM;@');
  assertValidFormat('[$-1010409]0.000%');
  assertValidFormat('[$-1010409]General');
  assertValidFormat('[$-1010409]d/m/yyyy\\ h:mm\\ AM/PM;@');
  assertValidFormat('[$-1010409]dddd, mmmm dd, yyyy');
  assertValidFormat('[$-1010409]m/d/yyyy');
  assertValidFormat('[$-1409]h:mm:ss\\ AM/PM;@');
  assertValidFormat('[$-2000000]h:mm:ss;@');
  assertValidFormat('[$-2010401]d/mm/yyyy\\ h:mm\\ AM/PM;@');
  assertValidFormat('[$-4000439]h:mm:ss\\ AM/PM;@');
  assertValidFormat('[$-4010439]d/m/yyyy\\ h:mm\\ AM/PM;@');
  assertValidFormat('[$-409]AM/PM\\ hh:mm:ss;@');
  assertValidFormat('[$-409]d/m/yyyy\\ hh:mm;@');
  assertValidFormat('[$-409]d\\-mmm;@');
  assertValidFormat('[$-409]d\\-mmm\\-yy;@');
  assertValidFormat('[$-409]d\\-mmm\\-yyyy;@');
  assertValidFormat('[$-409]dd/mm/yyyy\\ hh:mm;@');
  assertValidFormat('[$-409]dd\\-mmm\\-yy;@');
  assertValidFormat('[$-409]h:mm:ss\\ AM/PM;@');
  assertValidFormat('[$-409]h:mm\\ AM/PM;@');
  assertValidFormat('[$-409]m/d/yy\\ h:mm\\ AM/PM;@');
  assertValidFormat('[$-409]mmm\\-yy;@');
  assertValidFormat('[$-409]mmmm\\ d\\,\\ yyyy;@');
  assertValidFormat('[$-409]mmmm\\-yy;@');
  assertValidFormat('[$-409]mmmmm;@');
  assertValidFormat('[$-409]mmmmm\\-yy;@');
  assertValidFormat('[$-40E]h\\ "óra"\\ m\\ "perckor"\\ AM/PM;@');
  assertValidFormat('[$-412]AM/PM\\ h"시"\\ mm"분"\\ ss"초";@');
  assertValidFormat('[$-41C]h:mm:ss\\.AM/PM;@');
  assertValidFormat('[$-449]hh:mm:ss\\ AM/PM;@');
  assertValidFormat('[$-44E]hh:mm:ss\\ AM/PM;@');
  assertValidFormat('[$-44F]hh:mm:ss\\ AM/PM;@');
  assertValidFormat('[$-D000409]h:mm\\ AM/PM;@');
  assertValidFormat('[$-D010000]d/mm/yyyy\\ h:mm\\ "น.";@');
  assertValidFormat('[$-F400]h:mm:ss\\ AM/PM');
  assertValidFormat('[$-F800]dddd\\,\\ mmmm\\ dd\\,\\ yyyy');
  assertValidFormat('[$AUD]\\ #,##0.00');
  assertValidFormat('[$RD$-1C0A]#,##0.00;[Red]\\-[$RD$-1C0A]#,##0.00');
  assertValidFormat('[$SFr.-810]\\ #,##0.00_);[Red]\\([$SFr.-810]\\ #,##0.00\\)');
  assertValidFormat('[$£-809]#,##0.00;[Red][$£-809]#,##0.00');
  assertValidFormat('[$¥-411]#,##0.00');
  assertValidFormat('[$¥-804]#,##0.00');
  assertValidFormat('[<0]"";0%');
  assertValidFormat('[<=9999999]###\\-####;\\(###\\)\\ ###\\-####');
  assertValidFormat('[=0]?;#,##0.00');
  assertValidFormat('[=0]?;0%');
  assertValidFormat('[=0]?;[<4.16666666666667][hh]:mm:ss;[hh]:mm');
  assertValidFormat('[>999999]#,,"M";[>999]#,"K";#');
  assertValidFormat('[>999999]#.000,,"M";[>999]#.000,"K";#.000');
  assertValidFormat("[>=100000]0.000\\ \\\";[Red]0.000\\ \\<\\ \\>\\ \\\"\\ \\&\\ \\'\\ ");
  assertValidFormat('[>=100000]0.000\\ \\<;[Red]0.000\\ \\>');
  assertValidFormat('[BLACK]@');
  assertValidFormat('[BLUE]GENERAL');
  assertValidFormat('[Black]@');
  assertValidFormat('[Blue]General');
  assertValidFormat('[CYAN]@');
  assertValidFormat('[Cyan]@');
  assertValidFormat('[DBNum1][$-804]AM/PMh"时"mm"分";@');
  assertValidFormat('[DBNum1][$-804]General');
  assertValidFormat('[DBNum1][$-804]h"时"mm"分";@');
  assertValidFormat('[$-1004]dddd\\,\\ d\\ mmmm\\,\\ yyyy;@');
  assertValidFormat('[$-101040D]d\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-101042A]d\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-140C]dddd\\ "YeahWoo!"\\ ddd\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-2C0A]dddd\\ d" de "mmmm" de "yyyy;@');
  assertValidFormat('[$-402]dd\\ mmmm\\ yyyy\\ "г.";@');
  assertValidFormat('[$-403]dddd\\,\\ d" / "mmmm" / "yyyy;@');
  assertValidFormat('[$-405]d\\.\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-408]d\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-40B]d\\.\\ mmmm\\t\\a\\ yyyy;@');
  assertValidFormat('[$-40C]d/mmm/yyyy;@');
  assertValidFormat('[$-40E]yyyy/\\ mmmm\\ d\\.;@');
  assertValidFormat('[$-40F]dd\\.\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-410]d\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-415]d\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-416]d\\ \\ mmmm\\,\\ yyyy;@');
  assertValidFormat('[$-418]d\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-41A]d\\.\\ mmmm\\ yyyy\\.;@');
  assertValidFormat('[$-41B]d\\.\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-41D]"den "\\ d\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-420]dddd\\,\\ dd\\ mmmm\\,\\ yyyy;@');
  assertValidFormat('[$-421]dd\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-424]dddd\\,\\ d\\.\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-425]dddd\\,\\ d\\.\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-426]dddd\\,\\ yyyy". gada "d\\.\\ mmmm;@');
  assertValidFormat('[$-427]yyyy\\ "m."\\ mmmm\\ d\\ "d.";@');
  assertValidFormat('[$-42B]dddd\\,\\ d\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-42C]d\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-42D]yyyy"(e)ko"\\ mmmm"ren"\\ d"a";@');
  assertValidFormat('[$-42F]dddd\\,\\ dd\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-437]yyyy\\ \\წ\\ლ\\ი\\ს\\ dd\\ mm\\,\\ dddd;@');
  assertValidFormat('[$-438]d\\.\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-43F]d\\ mmmm\\ yyyy\\ "ж.";@');
  assertValidFormat('[$-444]d\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-449]dd\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-44E]d\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-44F]dd\\ mmmm\\ yyyy\\ dddd;@');
  assertValidFormat('[$-457]dd\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-813]dddd\\ d\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-81A]dddd\\,\\ d\\.\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-82C]d\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-843]yyyy\\ "й""и""л"\\ d/mmmm;@');
  assertValidFormat('[$-C07]dddd\\,\\ dd\\.\\ mmmm\\ yyyy;@');
  assertValidFormat('[$-FC19]yyyy\\,\\ dd\\ mmmm;@');
  assertValidFormat('[$-FC22]d\\ mmmm\\ yyyy" р.";@');
  assertValidFormat('[$-FC23]d\\ mmmm\\ yyyy;@');
  assertValidFormat('[GREEN]#,###');
  assertValidFormat('[Green]#,###');
  assertValidFormat('[HH]');
  assertValidFormat('[$-2060401]d/mm/yyyy\\ h:mm\\ AM/PM;@');
  assertValidFormat('[$-2060401]d\\ mmmm\\ yyyy;@');
  assertValidFormat('[H]');
  assertValidFormat('[$-411]gggyy"年"m"月"d"日"\\ dddd;@');
  assertValidFormat('[MAGENTA]0.00');
  assertValidFormat('[Magenta]0.00');
  assertValidFormat('[RED]#.##');
  assertValidFormat('[Red]#.##');
  assertValidFormat('[Red][<-25]General;[Blue][>25]General;[Green]General;[Yellow]General\\ ');
  assertValidFormat('[Red][<=-25]General;[Blue][>=25]General;[Green]General;[Yellow]General');
  assertValidFormat('[Red][<>50]General;[Blue]000');
  assertValidFormat('[Red][=50]General;[Blue]000');
  assertValidFormat('[SS]');
  assertValidFormat('[S]');
  assertValidFormat('[DBNum1][$-404]y"年"m"月"d"日";@');
  assertValidFormat('[WHITE]0.0');
  assertValidFormat('[White]0.0');
  assertValidFormat('[YELLOW]@');
  assertValidFormat('[Yellow]@');
  assertValidFormat('[h]');
  assertValidFormat('[h]:mm:ss');
  assertValidFormat('[h]:mm:ss;@');
  assertValidFormat('[h]\\.mm" Uhr ";@');
  assertValidFormat('[hh]');
  assertValidFormat('[s]');
  assertValidFormat('[ss]');
  assertValidFormat('\\#\\r\\e\\c');
  assertValidFormat('\\$#,##0_);[Red]"($"#,##0\\)');
  assertValidFormat('\\$0.00');
  assertValidFormat('\\C\\O\\B\\ \\o\\n\\ @');
  assertValidFormat('\\C\\R\\O\\N\\T\\A\\B\\ \\o\\n\\ @');
  assertValidFormat('\\R\\e\\s\\u\\l\\t\\ \\o\\n\\ @');
  assertValidFormat('\\S\\Q\\L\\ \\:\\ @');
  assertValidFormat('\\S\\Q\\L\\ \\R\\e\\q\\u\\e\\s\\t\\ \\f\\o\\r\\ @');
  assertValidFormat('\\c\\c\\c?????0"aaaa"0"bbbb"000000.00%');
  assertValidFormat('\\u\\n\\t\\i\\l\\ h:mm;@');
  assertValidFormat('_ "￥"* #,##0.00_ "Positive";_ "￥"* \\-#,##0.00_ ;_ "￥"* "-"??_ "Negtive";_ @_ \\ "Zero"');
  assertValidFormat('_ * #,##0.00_)[$﷼-429]_ ;_ * \\(#,##0.00\\)[$﷼-429]_ ;_ * "-"??_)[$﷼-429]_ ;_ @_ ');
  assertValidFormat('_ * #,##0_ ;_ * \\-#,##0_ ;[Red]_ * "-"_ ;_ @_ ');
  assertValidFormat('_("$"* #,##0.00_);_("$"* \\(#,##0.00\\);_("$"* "-"??_);_(@_)');
  assertValidFormat('_("$"* #,##0_);_("$"* \\(#,##0\\);_("$"* "-"??_);_(@_)');
  assertValidFormat('_("$"* #,##0_);_("$"* \\(#,##0\\);_("$"* "-"_);_(@_)');
  assertValidFormat('_(* #,##0.0000_);_(* \\(#,##0.0000\\);_(* "-"??_);_(@_)');
  assertValidFormat('_(* #,##0.000_);_(* \\(#,##0.000\\);_(* "-"??_);_(@_)');
  assertValidFormat('_(* #,##0.00_);_(* \\(#,##0.00\\);_(* "-"??_);_(@_)');
  assertValidFormat('_(* #,##0.0_);_(* \\(#,##0.0\\);_(* "-"??_);_(@_)');
  assertValidFormat('_(* #,##0_);_(* \\(#,##0\\);_(* "-"??_);_(@_)');
  assertValidFormat('_(* #,##0_);_(* \\(#,##0\\);_(* "-"_);_(@_)');
  assertValidFormat('_([$ANG]\\ * #,##0.0_);_([$ANG]\\ * \\(#,##0.0\\);_([$ANG]\\ * "-"?_);_(@_)');
  assertValidFormat('_-"€"\\ * #,##0.00_-;_-"€"\\ * #,##0.00\\-;_-"€"\\ * "-"??_-;_-@_-');
  assertValidFormat('_-* #,##0.00" TL"_-;\\-* #,##0.00" TL"_-;_-* \\-??" TL"_-;_-@_-');
  assertValidFormat('_-* #,##0.00" €"_-;\\-* #,##0.00" €"_-;_-* \\-??" €"_-;_-@_-');
  assertValidFormat('_-* #,##0.00\\ "р."_-;\\-* #,##0.00\\ "р."_-;_-* "-"??\\ "р."_-;_-@_-');
  assertValidFormat('_-* #,##0.00\\ "€"_-;\\-* #,##0.00\\ "€"_-;_-* "-"??\\ "€"_-;_-@_-');
  assertValidFormat('_-* #,##0.00\\ [$€-407]_-;\\-* #,##0.00\\ [$€-407]_-;_-* \\-??\\ [$€-407]_-;_-@_-');
  assertValidFormat('_-* #,##0.0\\ _F_-;\\-* #,##0.0\\ _F_-;_-* "-"??\\ _F_-;_-@_-');
  assertValidFormat('_-* #,##0\\ "€"_-;\\-* #,##0\\ "€"_-;_-* "-"\\ "€"_-;_-@_-');
  assertValidFormat('_-* #,##0_-;\\-* #,##0_-;_-* "-"??_-;_-@_-');
  assertValidFormat('_-\\$* #,##0.0_ ;_-\\$* \\-#,##0.0\\ ;_-\\$* "-"?_ ;_-@_ ');
  assertValidFormat('d');
  assertValidFormat('d-mmm');
  assertValidFormat('d-mmm-yy');
  assertValidFormat('d/m');
  assertValidFormat('d/m/yy;@');
  assertValidFormat('d/m/yyyy;@');
  assertValidFormat('d/mm/yy;@');
  assertValidFormat('d/mm/yyyy;@');
  assertValidFormat('d\\-mmm');
  assertValidFormat('d\\-mmm\\-yyyy');
  assertValidFormat('dd');
  assertValidFormat('dd"-"mmm"-"yyyy');
  assertValidFormat('dd/m/yyyy');
  assertValidFormat('dd/mm/yy');
  assertValidFormat('dd/mm/yy;@');
  assertValidFormat('dd/mm/yy\\ hh:mm');
  assertValidFormat('dd/mm/yyyy');
  assertValidFormat('dd/mm/yyyy\\ hh:mm:ss');
  assertValidFormat('dd/mmm');
  assertValidFormat('dd\\-mm\\-yy');
  assertValidFormat('dd\\-mmm\\-yy');
  assertValidFormat('dd\\-mmm\\-yyyy\\ hh:mm:ss.000');
  assertValidFormat('dd\\/mm\\/yy');
  assertValidFormat('dd\\/mm\\/yyyy');
  assertValidFormat('ddd');
  assertValidFormat('dddd');
  assertValidFormat('dddd, mmmm dd, yyyy');
  assertValidFormat('h');
  assertValidFormat('h"时"mm"分"ss"秒";@');
  assertValidFormat('h"時"mm"分"ss"秒";@');
  assertValidFormat('h:mm');
  assertValidFormat('h:mm AM/PM');
  assertValidFormat('h:mm:ss');
  assertValidFormat('h:mm:ss AM/PM');
  assertValidFormat('h:mm:ss;@');
  assertValidFormat('h:mm;@');
  assertValidFormat('h\\.mm" Uhr ";@');
  assertValidFormat('h\\.mm" h";@');
  assertValidFormat('h\\.mm" u.";@');
  assertValidFormat('hh":"mm AM/PM');
  assertValidFormat('hh:mm:ss');
  assertValidFormat('hh:mm:ss\\ AM/PM');
  assertValidFormat('hh\\.mm" h";@');
  assertValidFormat('hhm');
  assertValidFormat('hhmm');
  assertValidFormat('m"月"d"日"');
  assertValidFormat('m/d/yy');
  assertValidFormat('m/d/yy h:mm');
  assertValidFormat('m/d/yy;@');
  assertValidFormat('m/d/yy\\ h:mm');
  assertValidFormat('m/d/yy\\ h:mm;@');
  assertValidFormat('m/d/yyyy');
  assertValidFormat('m/d/yyyy;@');
  assertValidFormat('m/d/yyyy\\ h:mm:ss;@');
  assertValidFormat('m/d;@');
  assertValidFormat('m\\/d\\/yyyy');
  assertValidFormat('mm/dd');
  assertValidFormat('mm/dd/yy');
  assertValidFormat('mm/dd/yy;@');
  assertValidFormat('mm/dd/yyyy');
  assertValidFormat('mm:ss');
  assertValidFormat('mm:ss.0;@');
  assertValidFormat('mmm d, yyyy');
  assertValidFormat('mmm" "d", "yyyy');
  assertValidFormat('mmm-yy');
  assertValidFormat('mmm-yy;@');
  assertValidFormat('mmm/yy');
  assertValidFormat('mmm\\-yy');
  assertValidFormat('mmm\\-yy;@');
  assertValidFormat('mmm\\-yyyy');
  assertValidFormat('mmmm\\ d\\,\\ yyyy');
  assertValidFormat('mmmm\\ yyyy');
  assertValidFormat('mmss.0');
  assertValidFormat('s');
  assertValidFormat('ss');
  assertValidFormat('yy');
  assertValidFormat('yy/mm/dd');
  assertValidFormat('yy\\.mm\\.dd');
  assertValidFormat('yym');
  assertValidFormat('yymm');
  assertValidFormat('yymmm');
  assertValidFormat('yymmmm');
  assertValidFormat('yymmmmm');
  assertValidFormat('yyyy');
  assertValidFormat('yyyy"년"\\ m"월"\\ d"일";@');
  assertValidFormat('yyyy-m-d h:mm AM/PM');
  assertValidFormat('yyyy-mm-dd');
  assertValidFormat('yyyy/mm/dd');
  assertValidFormat('yyyy\\-m\\-d\\ hh:mm:ss');
  assertValidFormat('yyyy\\-mm\\-dd');
  assertValidFormat('yyyy\\-mm\\-dd;@');
  assertValidFormat('yyyy\\-mm\\-dd\\ h:mm');
  assertValidFormat('yyyy\\-mm\\-dd\\Thh:mm');
  assertValidFormat('yyyy\\-mm\\-dd\\Thhmmss.000');
});
